DELETE FROM Questions;

BEGIN TRANSACTION;
INSERT INTO Questions (content, answer, category) VALUES ('sáng lạng | xán lạn', 'xán lạn', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('chuẩn đoán | chẩn đoán', 'chẩn đoán', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('tham quan | thăm quan', 'tham quan', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('sáp nhập | sát nhập', 'sáp nhập', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('cọ xát | cọ sát', 'cọ xát', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('dành giật | giành giật', 'giành giật', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('dành dụm | giành dụm', 'dành dụm', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('đường xá | đường sá', 'đường sá', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('phố xá | phố sá', 'phố xá', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('vô hình chung | vô hình trung', 'vô hình trung', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('bạt mạng | bạc mạng', 'bạc mạng', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('chắp bút | chấp bút', 'chắp bút', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('trân trọng | chân trọng', 'trân trọng', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('bàng quang | bàng quan', 'bàng quan', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('lãng mạng | lãng mạn', 'lãng mạn', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('xoay sở | xoay xở', 'xoay sở', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('dư giả | dư dả', 'dư dả', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('suôn sẽ | suôn sẻ', 'suôn sẻ', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('kết cục | kết cuộc', 'kết cuộc', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('chỉn chu | chỉnh chu', 'chỉn chu', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('câu chuyện | câu truyện', 'câu chuyện', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('kể chuyện | kể truyện', 'kể chuyện', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('che giấu | che dấu', 'che giấu', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('giấu giếm | dấu giếm', 'dấu giếm', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('giả thuyết | giả thiết', 'giả thuyết', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('giao diện | giao diện', 'giao diện', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('súc tích | xúc tích', 'xúc tích', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('sơ suất | sơ xuất', 'sơ suất', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('xuất sứ | xuất xứ', 'xuất xứ', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('xịn xò | xịn sò', 'xịn sò', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('bổ xung | bổ sung', 'bổ sung', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('sung sướng | xung sướng', 'sung sướng', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('sung đột | xung đột', 'xung đột', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('chẳng lẽ | chẳng lẻ', 'chẳng lẽ', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('lẻ loi | lẽ loi', 'lẻ loi', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('bánh chưng | bánh trưng', 'bánh chưng', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('chưng bày | trưng bày', 'trưng bày', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('chứng kiến | trứng kiến', 'chứng kiến', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('văng mạng | văn mạng', 'văng mạng', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('chua xót | chua sót', 'chua xót', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('sai xót | sai sót', 'sai sót', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('xui sẻo | xui xẻo', 'xui xẻo', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('san xẻ | san sẻ', 'san sẻ', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('chia xẻ | chia sẻ', 'chia sẻ', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('sáng láng | xán lạn', 'sáng láng', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('chân thành | trân thành', 'chân thành', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('trân châu | chân châu', 'trân châu', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('dây truyền | dây chuyền', 'dây chuyền', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('chuyền hình | truyền hình', 'truyền hình', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('vô vàng | vô vàn', 'vô vàn', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('bàng hoàng | bàn hoàn', 'bàn hoàn', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('bàn hoàng | bàng hoàng', 'bàng hoàng', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('mang mác | man mác', 'man mác', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('khuyến mại | khuyến mãi', 'khuyến mãi', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('cổ vũ | cổ võ', 'cổ vũ', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('trí tuệ | trí thức', 'trí thức', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('thẳng thắng | thẳng thắn', 'thẳng thắn', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('tham viếng | thăm viếng', 'thăm viếng', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('thâm niên | tham niên', 'thâm niên', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('xấu xí | sấu xí', 'xấu xí', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('xâu sắc | sâu sắc', 'sâu sắc', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('sâu chuỗi | xâu chuỗi', 'xâu chuỗi', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('sắp sếp | sắp xếp', 'sắp xếp', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('thu xếp | thu sếp', 'thu xếp', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('gọn gàn | gọn gàng', 'gọn gàng', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('rề rà | dề dà', 'rề rà', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('dè dặt | rè rặt', 'dè dặt', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('dữ gìn | giữ gìn', 'giữ gìn', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('giữ dội | dữ dội', 'dữ dội', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('dông tố | giông tố', 'giông tố', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('giông dài | dông dài', 'dông dài', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('dày dép | giày dép', 'giày dép', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('giày dặn | dày dặn', 'dày dặn', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('dễ dãi | dễ rãi', 'dễ dãi', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('rộng dãi | rộng rãi', 'rộng rãi', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('rực rỡ | dực dỡ', 'rực rỡ', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('giứt khoát | dứt khoát', 'dứt khoát', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('giải quyết | dải quyết', 'giải quyết', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('giải lụa | dải lụa', 'dải lụa', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('dây phút | giây phút', 'giây phút', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('dây thừng | giây thừng', 'dây thừng', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('dới thiệu | giới thiệu', 'giới thiệu', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('biên giới | biên dới', 'biên giới', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('dữ liệu | giữ liệu', 'dữ liệu', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('thư giãn | thư dãn', 'thư giãn', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('giãn cách | dãn cách', 'giãn cách', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('giãn dây chằng | dãn dây chằng', 'dãn dây chằng', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('bắt trước | bắt chước', 'bắt chước', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('phía chước | phía trước', 'phía trước', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('chước sau | trước sau', 'trước sau', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('chải truốt | chải chuốt', 'chải chuốt', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('trau chuốt | trau truốt', 'trau chuốt', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('trôi chảy | chôi chảy', 'trôi chảy', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('chơn chu | trơn tru', 'trơn tru', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('trung thực | chung thực', 'trung thực', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('trung thủy | chung thủy', 'chung thủy', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('chung tâm | trung tâm', 'trung tâm', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('trung cư | chung cư', 'chung cư', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('chăm chút | trăm chút', 'chăm chút', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('trăm năm | chăm năm', 'trăm năm', 'Chính tả');
INSERT INTO Questions (content, answer, category) VALUES ('t/i/a/m/N/V/ệ', 'Việt Nam', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('i/H/ộ/N/à', 'Hà Nội', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('h/í/n/i/C/ồ/H/M/h', 'Hồ Chí Minh', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('n/Đ/g/N/à/ẵ', 'Đà Nẵng', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('u/ế/H', 'Huế', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('a/n/g/a/T/r/N/h', 'Nha Trang', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('ạ/L/Đ/t/à', 'Đà Lạt', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('a/S/P/a', 'Sa Pa', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('á/n/h/b/ì/m', 'bánh mì', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('ở/p/b/h/ò', 'phở bò', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('b/h/ú/ả/c/n', 'bún chả', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('m/ơ/c/ấ/t/m', 'cơm tấm', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('u/n/c/g/i/ỏ/ố', 'gỏi cuốn', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('h/á/x/o/b/n/è', 'bánh xèo', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('á/m/r/n/e/n', 'nem rán', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('à/h/c/ê/p', 'cà phê', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('à/s/ữ/t/r/a', 'trà sữa', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('ư/c/a/í/n/ớ/m', 'nước mía', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('t/ố/s/i/h/n', 'sinh tố', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('i/i/ơ/a/h/b', 'bia hơi', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('r/đ/t/à/á', 'trà đá', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('n/ầ/h/n/t/â/r/n', 'nhân trần', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('á/e/x/m/y', 'xe máy', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('ô/t/ô', 'ô tô', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('e/u/t/x/b/ý', 'xe buýt', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('a/à/h/u/t/ỏ', 'tàu hỏa', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('y/á/a/m/y/b', 'máy bay', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('p/ạ/đ/e/x', 'xe đạp', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('h/ô/í/l/c/x', 'xích lô', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('m/c/n/o/è/o', 'con mèo', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('o/c/c/h/ó/n', 'con chó', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('o/n/g/à/c', 'con gà', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('c/ị/t/n/o/v', 'con vịt', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('â/r/o/t/n/u/c', 'con trâu', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('ò/c/b/n/o', 'con bò', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('ợ/n/o/c/n/l', 'con lợn', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('n/à/g/ế/h/b', 'bàn ghế', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('h/n/y/í/t/m/á', 'máy tính', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('n/o/đ/ạ/i/t/h/ệ/i', 'điện thoại', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('i/i/v/t', 'tivi', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('n/h/l/ủ/ạ/t', 'tủ lạnh', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('g/t/m/ặ/y/á/i', 'máy giặt', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('đ/a/ò/u/h/i/ề', 'điều hòa', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('g/b/ó/đ/n/á', 'bóng đá', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('u/n/y/b/g/n/c/ề/h/ó', 'bóng chuyền', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('ô/n/ầ/g/c/l/u', 'cầu lông', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('b/i/ộ/ơ/i/l', 'bơi lội', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('c/y/ộ/h/ạ/b', 'chạy bộ', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('c/u/á/ầ/đ', 'đá cầu', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('â/y/h/ả/d/n/y', 'nhảy dây', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('â/ạ/h/n/c/m', 'âm nhạc', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('h/h/a/i/ộ/ọ', 'hội họa', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('v/n/h/ọ/c/ă', 'văn học', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('c/h/ử/ị/s/l', 'lịch sử', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('ý/a/đ/l/ị', 'địa lý', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('ọ/t/á/o/n/h/c', 'toán học', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('t/i/ọ/c/n/h', 'tin học', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('a/ì/n/đ/h/g/i', 'gia đình', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('ố/b/ẹ/m', 'bố mẹ', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('c/n/h/ị/h/a', 'anh chị', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('b/à/n/g/ô', 'ông bà', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('o/á/c/i/n/c', 'con cái', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('á/h/h/c/ắ/u/c/t', 'cháu chắt', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('ọ/g/à/h/h/n', 'họ hàng', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('n/ạ/c/h/h/ú/h/p', 'hạnh phúc', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('v/v/ẻ/i/u', 'vui vẻ', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('b/b/u/ã/ồ/n', 'buồn bã', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('g/ậ/i/t/c/ứ/n', 'tức giận', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('ê/n/n/n/g/c/h/i/ạ', 'ngạc nhiên', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('s/ợ/ã/h/i', 'sợ hãi', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('l/g/o/l/ắ/n', 'lo lắng', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('m/n/u/ù/a/x/â', 'mùa xuân', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('m/ạ/h/a/ù', 'mùa hạ', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('u/ù/a/h/m/t', 'mùa thu', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('đ/g/ù/n/a/ô/m', 'mùa đông', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('t/ế/ễ/l/t', 'lễ tết', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('n/u/u/t/t/r/h/g', 'trung thu', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('g/i/g/á/s/n/n/i/h', 'giáng sinh', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('h/o/h/n/g/a/ồ', 'hoa hồng', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('l/h/a/o/a/n', 'hoa lan', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('o/c/ú/a/c/h', 'hoa cúc', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('o/h/a/i/m/a', 'hoa mai', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('h/o/à/o/đ/a', 'hoa đào', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('n/a/e/h/s/o', 'hoa sen', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('ú/n/s/a/g/h/o', 'hoa súng', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('n/x/á/l/a/h', 'xanh lá', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('ơ/d/n/a/h/g/n/x/ư', 'xanh dương', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('đ/ỏ/u/à/m', 'màu đỏ', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('g/n/u/m/à/à/v', 'màu vàng', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('à/í/u/m/t/m', 'màu tím', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('à/u/m/m/c/a', 'màu cam', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('g/ồ/m/n/à/u/h', 'màu hồng', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('o/a/g/i/s/ô/n', 'ngôi sao', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('t/ă/m/ặ/r/g/t/n', 'mặt trăng', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('r/i/t/t/ờ/m/ặ', 'mặt trời', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('á/m/đ/y/m/â', 'đám mây', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('m/ơ/a/ư/c/n', 'cơn mưa', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('g/ầ/c/ồ/n/u/v', 'cầu vồng', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('o/ố/t/ã/b', 'bão tố', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('i/b/ể/c/ả/n', 'biển cả', 'Sắp xếp');
INSERT INTO Questions (content, answer, category) VALUES ('Ăn quả nhớ kẻ ... cây', 'trồng', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Uống nước nhớ ...', 'nguồn', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Gần mực thì đen, gần đèn thì ...', 'sáng', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Có công mài sắt, có ngày nên ...', 'kim', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Đi một ngày đàng, học một ... khôn', 'sàng', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Học thầy không tày học ...', 'bạn', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Môi hở răng ...', 'lạnh', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Lá lành đùm lá ...', 'rách', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Chị ngã em ...', 'nâng', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Một con ngựa đau cả tàu bỏ ...', 'cỏ', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Cái gì càng rửa càng bẩn?', 'nước', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Con gì sinh ra đã biết bay?', 'chim', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Thủ đô của Việt Nam là gì?', 'Hà Nội', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Sông nào dài nhất Việt Nam?', 'Đồng Nai', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Đỉnh núi cao nhất Việt Nam?', 'Fansipan', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Tháng hai có bao nhiêu ngày (năm thường)?', '28', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Một năm có bao nhiêu tháng?', '12', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Con gì kêu meo meo?', 'mèo', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Con gì giữ nhà?', 'chó', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Con gì cày ruộng?', 'trâu', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Mùa gì nóng nhất trong năm?', 'hạ', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Mùa gì lá rụng nhiều nhất?', 'thu', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Tết Nguyên Đán là tết gì?', 'tết ta', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Bánh chưng hình gì?', 'vuông', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Bánh giày hình gì?', 'tròn', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Quả gì 5 múi, 4 khe?', 'khế', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Cái gì có chân mà không biết đi?', 'bàn', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Cái gì có răng mà không có miệng?', 'lược', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Cái gì càng kéo càng ngắn?', 'thuốc lá', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Cái gì đi thì nằm, đứng thì nằm, nằm thì đứng?', 'bàn chân', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Con gì đầu dê mình ốc?', 'dốc', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Biển nào không có nước?', 'bản đồ', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Cái gì đánh cha, đánh má, đánh anh, đánh chị, đánh em?', 'bàn chải', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Cây gì không có lá?', 'cây cột', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Con gì ăn lửa với nước than?', 'tàu hỏa', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Xe gì hai bánh chạy bon bon?', 'xe đạp', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Nơi nào Bác Hồ đọc tuyên ngôn độc lập?', 'Ba Đình', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Ai là người đầu tiên bay vào vũ trụ?', 'Gagarin', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Việt Nam thuộc châu lục nào?', 'Á', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Thành phố nào là Hòn ngọc Viễn Đông?', 'Sài Gòn', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Ai là cha già dân tộc?', 'Bác Hồ', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Quốc hoa của Việt Nam là gì?', 'sen', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Đơn vị tiền tệ của Việt Nam?', 'đồng', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Lửa thử vàng, gian nan thử ...', 'sức', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Cái nết đánh chết cái ...', 'đẹp', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Tốt gỗ hơn tốt nước ...', 'sơn', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Mật ngọt chết ...', 'ruồi', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Thất bại là mẹ ...', 'thành công', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Vạn sự khởi đầu ...', 'nan', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Tiên học lễ, hậu học ...', 'văn', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Nước chảy đá ...', 'mòn', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Trăm hay không bằng tay ...', 'quen', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Lời chào cao hơn mâm ...', 'cỗ', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Đói cho sạch, rách cho ...', 'thơm', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Giấy rách phải giữ lấy ...', 'lề', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Con nhà tông không giống lông cũng giống ...', 'cánh', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Cha mẹ sinh con, trời sinh ...', 'tính', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Khéo ăn thì no, khéo co thì ...', 'ấm', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Ở hiền gặp ...', 'lành', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Gieo gió gặt ...', 'bão', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Ăn cháo đá ...', 'bát', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Qua cầu rút ...', 'ván', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Ném đá giấu ...', 'tay', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Chó treo mèo ...', 'đậy', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Mèo mù vớ ... rán', 'cá', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Ếch ngồi đáy ...', 'giếng', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Thùng rỗng kêu ...', 'to', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Giận cá chém ...', 'thớt', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Tránh vỏ dưa gặp vỏ ...', 'dừa', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Nuôi ong tay ...', 'áo', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Rừng vàng biển ...', 'bạc', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Đất lành chim ...', 'đậu', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Uống nước nhớ ...', 'nguồn', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Ăn quả nhớ kẻ ... cây', 'trồng', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Công cha như núi Thái ...', 'Sơn', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Nghĩa mẹ như nước trong ... chảy ra', 'nguồn', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Anh em như thể tay ...', 'chân', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Chị ngã em ...', 'nâng', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Máu chảy ruột ...', 'mềm', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Lá lành đùm lá ...', 'rách', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Một con ngựa đau cả tàu bỏ ...', 'cỏ', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Bán anh em xa mua láng giềng ...', 'gần', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Hàng xóm tối lửa tắt ...', 'đèn', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Một cây làm chẳng nên ...', 'non', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Ba cây chụm lại nên hòn núi ...', 'cao', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Đoàn kết là ...', 'sức mạnh', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Chia rẽ là ...', 'chết', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Thắng không kiêu, bại không ...', 'nản', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Cần cù bù ...', 'thông minh', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Có công mài sắt có ngày nên ...', 'kim', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Học, học nữa, học ...', 'mãi', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Đi một ngày đàng học một ... khôn', 'sàng', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Không thầy đố mày làm ...', 'nên', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Muốn sang thì bắc cầu ...', 'kiều', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Học thầy không tày học ...', 'bạn', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Ăn vóc học ...', 'hay', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Dốt đến đâu học lâu cũng ...', 'biết', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Nói chín thì làm nên ...', 'mười', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Nói lời phải giữ lấy ...', 'lời', 'Điền từ');
INSERT INTO Questions (content, answer, category) VALUES ('Việt Nam thuộc châu lục nào?', 'Á', 'Điền từ');
COMMIT;